---
version: "2"

linters:
  enable:
  - depguard
  - gocritic
  - gosec
  - loggercheck
  - misspell
  - revive
  settings:
    depguard:
      rules:
        main:
          deny:
          - pkg: sync/atomic
            desc: "Use go.uber.org/atomic instead of sync/atomic"
          - pkg: github.com/go-kit/kit/log
            desc: "Use github.com/go-kit/log instead of github.com/go-kit/kit/log"
    errcheck:
      exclude-functions:
      # Don't flag lines such as "io.Copy(io.Discard, resp.Body)".
      - io.Copy
      # The next two are used in HTTP handlers, any error is handled by the server itself.
      - io.WriteString
      - (net/http.ResponseWriter).Write
      # No need to check for errors on server's shutdown.
      - (*net/http.Server).Shutdown
  exclusions:
    presets:
    - std-error-handling
    - common-false-positives
    - legacy
    - comments
    rules:
    - path: _test.go
      linters:
      - depguard
      - errcheck
      - gosec

formatters:
  enable:
  - gofumpt
  - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
