name: Build
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: install Go
        uses: actions/setup-go@v7
        with:
          go-version: 1.26.5
      - name: Lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
  build:
    name: Docker
    needs: lint
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/qustodio/uwsgi_exporter
          tags: |
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
